# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliExample < Formula
  desc "go-cli-example"
  homepage "https://github.com/sika-training-examples/go-cli-example"
  version "0.1.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.5/go-cli-example_v0.1.5_darwin_amd64.tar.gz"
      sha256 "6d275b10ff4c126a92614eced9ce51c835d92c66bc5a8bc8835362814cf866a4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.5/go-cli-example_v0.1.5_darwin_arm64.tar.gz"
      sha256 "de88d6c89dbb1d7b1517fd60d3f6196fe084f663a71b0cfaccd681a163b39f1d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.5/go-cli-example_v0.1.5_linux_amd64.tar.gz"
      sha256 "367cb9e4c9e0f03c17e6929f9ebf4a0b27a300dd9faaa34276e9b74be751f931"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.5/go-cli-example_v0.1.5_linux_arm64.tar.gz"
      sha256 "7cbdc247c2c3f465097a136663ba5d9faa87da606e11ea17fb4d400addfa5153"
    end
  end

  conflicts_with "go-cli-example-edge"

  def install
    bin.install "go-cli-example"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sika-training-examples/go-cli-example
  EOS
  end

  test do
    system "#{bin}/go-cli-example version"
  end
end
