# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliExample < Formula
  desc "go-cli-example"
  homepage "https://github.com/sika-training-examples/go-cli-example"
  version "0.1.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.6/go-cli-example_v0.1.6_darwin_amd64.tar.gz"
      sha256 "bd6857edeb2e344099e0850f22833a49f11e2aa816188d9a9a852b505b6d51b7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.6/go-cli-example_v0.1.6_darwin_arm64.tar.gz"
      sha256 "6332c5a1df0f5835cfd190f18810ab05479d484ddefabe6be8284f1a2d7e722d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.6/go-cli-example_v0.1.6_linux_amd64.tar.gz"
      sha256 "f72f32702705dce8a41542fd4f5c9302707e8fbb9d3f26fc8983f80e8341e27a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sika-training-examples/go-cli-example/releases/download/v0.1.6/go-cli-example_v0.1.6_linux_arm64.tar.gz"
      sha256 "f8445aa5de48514af8ea8e057395c17aa785b45843e499e1f39a9a9e1b536a71"
    end
  end

  conflicts_with "go-cli-example-edge"

  def install
    bin.install "go-cli-example"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sika-training-examples/go-cli-example
  EOS
  end

  test do
    system "#{bin}/go-cli-example version"
  end
end
